version: "3.8"

services:
  postgres:
    image: postgres:latest
    container_name: mrc_shop_db_container
    restart: always
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: 3115138Bg
      POSTGRES_DB: mrc_shop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
